### ISSUE TITLE
AttributeError: module 'pip' has no attribute 'operations'

### ISSUE THREAD

**Issue by jakezcruit** [nficano/python-lambda#108]
When I run 'lambda deploy' I get:

Gathering pip packages
Traceback (most recent call last):
  File "/Users/jacobschumaker/.virtualenvs/test/bin/lambda", line 230, in <module>
    cli()
  File "/Users/jacobschumaker/.virtualenvs/test/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jacobschumaker/.virtualenvs/test/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/jacobschumaker/.virtualenvs/test/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jacobschumaker/.virtualenvs/test/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jacobschumaker/.virtualenvs/test/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/jacobschumaker/.virtualenvs/test/bin/lambda", line 128, in deploy
    profile_name=profile,
  File "/Users/jacobschumaker/.virtualenvs/test/lib/python3.6/site-packages/aws_lambda/aws_lambda.py", line 109, in deploy
    local_package=local_package,
  File "/Users/jacobschumaker/.virtualenvs/test/lib/python3.6/site-packages/aws_lambda/aws_lambda.py", line 295, in build
    local_package=local_package,
  File "/Users/jacobschumaker/.virtualenvs/test/lib/python3.6/site-packages/aws_lambda/aws_lambda.py", line 430, in pip_install_to_target
    packages.extend(pip.operations.freeze.freeze())
AttributeError: module 'pip' has no attribute 'operations'

**Comment by moee** [comment]
I had the same problem, downgrading pip inside the virtualenv from version 10 to version 9 did the trick for me:

`pip install pip==9.0.3`

**Comment by jakezcruit** [comment]
Thanks, that worked for me too

**Comment by nficano** [comment]
fixed w/ pip 10 :)
