### ISSUE TITLE
Build and deploy issues with 3.2.2

### ISSUE THREAD

**Issue by loren** [nficano/python-lambda#117]
Hi, I've used `python-lambda` to build and deploy over a dozen lambdas but now I'm running into problems re-deploying existing lambdas and building new ones. Here's what my session looks like trying to follow the README to build and deploy the lambda bootstrapped by `lambda init`:

```
compy:workspace loren$ mkvirtualenv pylambda
New python executable in /Users/loren/.virtualenvs/pylambda/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/loren/.virtualenvs/pylambda/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/loren/.virtualenvs/pylambda/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/loren/.virtualenvs/pylambda/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/loren/.virtualenvs/pylambda/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/loren/.virtualenvs/pylambda/bin/get_env_details
(pylambda) compy:workspace loren$ mkdir pylambda
(pylambda) compy:workspace loren$ cd !$
cd pylambda
(pylambda) compy:pylambda loren$ python -V
Python 2.7.10
(pylambda) compy:pylambda loren$ pip -V
pip 10.0.1 from /Users/loren/.virtualenvs/pylambda/lib/python2.7/site-packages/pip (python 2.7)
(pylambda) compy:pylambda loren$ pip install python-lambda
Looking in indexes: https://pypi.org/simple, https://devpi:qSXgxGUuqS7mnJ8AeDKgK64Q@devpi.dev.primering.net/root/edge/
Collecting python-lambda
  Downloading https://files.pythonhosted.org/packages/9c/52/ee349fe8c89e50f9ef3344d8577751d3b8a2a6786ad45b2e9914a446b827/python_lambda-3.2.2-py2.py3-none-any.whl
Collecting click==6.6 (from python-lambda)
  Downloading https://files.pythonhosted.org/packages/1c/7c/10b4132dd952b6a04e37626258825b8aa8c1eb99545f2eb26a77c21efb55/click-6.6-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 738kB/s
Collecting six==1.10.0 (from python-lambda)
  Downloading https://files.pythonhosted.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl
Collecting futures (from python-lambda)
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting docutils==0.12 (from python-lambda)
  Downloading https://files.pythonhosted.org/packages/37/38/ceda70135b9144d84884ae2fc5886c6baac4edea39550f28bcd144c1234d/docutils-0.12.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 1.8MB/s
Collecting botocore==1.5.62 (from python-lambda)
  Downloading https://files.pythonhosted.org/packages/6c/05/71534a08a2ac83d7aad88d7b5246b45e0635645c4d4072d83a91f03f7d0f/botocore-1.5.62-py2.py3-none-any.whl (3.5MB)
    100% |████████████████████████████████| 3.5MB 1.9MB/s
Collecting boto3==1.4.4 (from python-lambda)
  Downloading https://files.pythonhosted.org/packages/91/60/649da03299624f524c8d0cd4c6c73c194023e85dd4938f1e7712ab6888bf/boto3-1.4.4-py2.py3-none-any.whl (127kB)
    100% |████████████████████████████████| 133kB 1.8MB/s
Collecting jmespath==0.9.0 (from python-lambda)
  Downloading https://files.pythonhosted.org/packages/64/2b/73af55c93f91941bd0c8c6cb1a3028cfd4c8dc4fe8ffe761dc60192dd82c/jmespath-0.9.0-py2.py3-none-any.whl
Collecting pyaml==15.8.2 (from python-lambda)
  Downloading https://files.pythonhosted.org/packages/59/19/7279d8d457471334901978345b2c3729eeed3bad8bbcc981a8066480c66a/pyaml-15.8.2.tar.gz
Collecting PyYAML==3.11 (from python-lambda)
Collecting python-dateutil==2.5.3 (from python-lambda)
  Downloading https://files.pythonhosted.org/packages/33/68/9eadc96f9899caebd98f55f942d6a8f3fb2b8f8e69ba81a0f771269897e9/python_dateutil-2.5.3-py2.py3-none-any.whl (201kB)
    100% |████████████████████████████████| 204kB 1.4MB/s
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3==1.4.4->python-lambda)
  Using cached https://files.pythonhosted.org/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl
Building wheels for collected packages: docutils, pyaml
  Running setup.py bdist_wheel for docutils ... done
  Stored in directory: /Users/loren/Library/Caches/pip/wheels/fa/da/e9/a23277185cb06d1ee65ed18636d04793f432ae70a622fcd7f2
  Running setup.py bdist_wheel for pyaml ... done
  Stored in directory: /Users/loren/Library/Caches/pip/wheels/25/7c/79/a52e0e0c4516d2cf49ac5628a44d584a58df779ed123af306a
Successfully built docutils pyaml
Installing collected packages: click, six, futures, docutils, jmespath, python-dateutil, botocore, s3transfer, boto3, PyYAML, pyaml, python-lambda
Successfully installed PyYAML-3.11 boto3-1.4.4 botocore-1.5.62 click-6.6 docutils-0.12 futures-3.2.0 jmespath-0.9.0 pyaml-15.8.2 python-dateutil-2.5.3 python-lambda-3.2.2 s3transfer-0.1.13 six-1.10.0
(pylambda) compy:pylambda loren$ lambda init
(pylambda) compy:pylambda loren$ lambda invoke
5.858
(pylambda) compy:pylambda loren$ lambda deploy
Gathering pip packages
Installing boto3==1.4.4
python-lambda 3.2.2 has requirement botocore==1.5.62, but you'll have botocore 1.5.95 which is incompatible.
python-lambda 3.2.2 has requirement docutils==0.12, but you'll have docutils 0.14 which is incompatible.
python-lambda 3.2.2 has requirement jmespath==0.9.0, but you'll have jmespath 0.9.3 which is incompatible.
python-lambda 3.2.2 has requirement python-dateutil==2.5.3, but you'll have python-dateutil 2.7.3 which is incompatible.
python-lambda 3.2.2 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
Installing botocore==1.5.62
python-lambda 3.2.2 has requirement docutils==0.12, but you'll have docutils 0.14 which is incompatible.
python-lambda 3.2.2 has requirement jmespath==0.9.0, but you'll have jmespath 0.9.3 which is incompatible.
python-lambda 3.2.2 has requirement python-dateutil==2.5.3, but you'll have python-dateutil 2.7.3 which is incompatible.
python-lambda 3.2.2 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
Installing click==6.6
Installing docutils==0.12
Installing futures==3.2.0
Installing jmespath==0.9.0
Installing pip==10.0.1
Installing pyaml==15.8.2
python-lambda 3.2.2 has requirement PyYAML==3.11, but you'll have pyyaml 3.12 which is incompatible.
Installing python-dateutil==2.5.3
python-lambda 3.2.2 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
Installing PyYAML==3.11
Installing s3transfer==0.1.13
boto3 1.4.4 has requirement botocore<1.6.0,>=1.5.0, but you'll have botocore 1.10.39 which is incompatible.
python-lambda 3.2.2 has requirement botocore==1.5.62, but you'll have botocore 1.10.39 which is incompatible.
python-lambda 3.2.2 has requirement docutils==0.12, but you'll have docutils 0.14 which is incompatible.
python-lambda 3.2.2 has requirement jmespath==0.9.0, but you'll have jmespath 0.9.3 which is incompatible.
python-lambda 3.2.2 has requirement python-dateutil==2.5.3, but you'll have python-dateutil 2.7.3 which is incompatible.
python-lambda 3.2.2 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
Installing setuptools==39.2.0
Installing six==1.10.0
Installing wheel==0.31.1
Installing wsgiref==0.1.2
Bundling: 'service.py'
Bundling: 'service.pyc'
Bundling: 'event.json'
Found credentials in shared credentials file: ~/.aws/credentials
Starting new HTTPS connection (1): lambda.us-east-1.amazonaws.com
Traceback (most recent call last):
  File "/Users/loren/.virtualenvs/pylambda/bin/lambda", line 230, in <module>
    cli()
  File "/Users/loren/.virtualenvs/pylambda/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/loren/.virtualenvs/pylambda/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/loren/.virtualenvs/pylambda/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/loren/.virtualenvs/pylambda/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/loren/.virtualenvs/pylambda/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/loren/.virtualenvs/pylambda/bin/lambda", line 128, in deploy
    profile_name=profile,
  File "/Users/loren/.virtualenvs/pylambda/lib/python2.7/site-packages/aws_lambda/aws_lambda.py", line 112, in deploy
    existing_config = get_function_config(cfg)
  File "/Users/loren/.virtualenvs/pylambda/lib/python2.7/site-packages/aws_lambda/aws_lambda.py", line 719, in get_function_config
    return client.get_function(FunctionName=function_name)
  File "/Users/loren/.virtualenvs/pylambda/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/loren/.virtualenvs/pylambda/lib/python2.7/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the GetFunction operation: The security token included in the request is invalid.
```

I can invoke the lambda locally just fine. It's the build step that seems to get tripped up on the package versions and then the deploy step seems to be complaining about a security issue.

Can anyone else follow the README and get a different outcome?

**Comment by bdrhoa** [comment]
Same here (I'm not worred about the 'Unable to locate credentials'):

```
(preproenv) Brads-MacBook-Pro:preprocessor bradrhoads$ lambda deploy
Gathering pip packages
Installing boto3==1.4.4
python-lambda 3.2.2 has requirement botocore==1.5.62, but you'll have botocore 1.5.95 which is incompatible.
python-lambda 3.2.2 has requirement docutils==0.12, but you'll have docutils 0.14 which is incompatible.
python-lambda 3.2.2 has requirement jmespath==0.9.0, but you'll have jmespath 0.9.3 which is incompatible.
python-lambda 3.2.2 has requirement python-dateutil==2.5.3, but you'll have python-dateutil 2.7.3 which is incompatible.
python-lambda 3.2.2 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
Installing botocore==1.5.62
python-lambda 3.2.2 has requirement docutils==0.12, but you'll have docutils 0.14 which is incompatible.
python-lambda 3.2.2 has requirement jmespath==0.9.0, but you'll have jmespath 0.9.3 which is incompatible.
python-lambda 3.2.2 has requirement python-dateutil==2.5.3, but you'll have python-dateutil 2.7.3 which is incompatible.
python-lambda 3.2.2 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
Installing click==6.6
Installing docutils==0.12
Installing futures==3.1.1
Installing jmespath==0.9.0
Installing pip==10.0.1
Installing pyaml==15.8.2
python-lambda 3.2.2 has requirement PyYAML==3.11, but you'll have pyyaml 3.13 which is incompatible.
Installing python-dateutil==2.5.3
python-lambda 3.2.2 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
Installing PyYAML==3.11
Installing s3transfer==0.1.13
python-lambda 3.2.2 has requirement botocore==1.5.62, but you'll have botocore 1.10.58 which is incompatible.
python-lambda 3.2.2 has requirement docutils==0.12, but you'll have docutils 0.14 which is incompatible.
python-lambda 3.2.2 has requirement jmespath==0.9.0, but you'll have jmespath 0.9.3 which is incompatible.
python-lambda 3.2.2 has requirement python-dateutil==2.5.3, but you'll have python-dateutil 2.7.3 which is incompatible.
python-lambda 3.2.2 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
boto3 1.4.4 has requirement botocore<1.6.0,>=1.5.0, but you'll have botocore 1.10.58 which is incompatible.
Installing setuptools==39.0.1
Installing six==1.10.0
Bundling: 'service.py'
Bundling: 'event.json'
Starting new HTTP connection (1): 169.254.169.254
Traceback (most recent call last):
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/bin/lambda", line 230, in <module>
    cli()
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/bin/lambda", line 128, in deploy
    profile_name=profile,
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/aws_lambda/aws_lambda.py", line 112, in deploy
    existing_config = get_function_config(cfg)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/aws_lambda/aws_lambda.py", line 719, in get_function_config
    return client.get_function(FunctionName=function_name)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/botocore/client.py", line 544, in _make_api_call
    operation_model, request_dict)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/botocore/endpoint.py", line 166, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/botocore/endpoint.py", line 150, in create_request
    operation_name=operation_model.name)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/botocore/signers.py", line 154, in sign
    auth.add_auth(request)
  File "/Users/bradrhoads/Dropbox/Documents/src/instantaudio/preproenv/lib/python3.6/site-packages/botocore/auth.py", line 339, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```
