### ISSUE TITLE
AttributeError: 'int' object has no attribute 'decode'

### ISSUE THREAD

**Issue by romelgomez** [nficano/python-lambda#128]
After doing a fresh Installation, and run:  `lambda deploy`

```
websocket-client==0.53.0
Werkzeug==0.14.1
whichcraft==0.4.1
wrapt==1.10.11
yarl==1.2.6
Traceback (most recent call last):
  File "/home/romel/.local/bin/lambda", line 237, in <module>
    cli()
  File "/home/romel/.local/lib/python3.6/site-packages/click/core.py", line722, in __call__
    return self.main(*args, **kwargs)
  File "/home/romel/.local/lib/python3.6/site-packages/click/core.py", line697, in main
    rv = self.invoke(ctx)
  File "/home/romel/.local/lib/python3.6/site-packages/click/core.py", line1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/romel/.local/lib/python3.6/site-packages/click/core.py", line895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/romel/.local/lib/python3.6/site-packages/click/core.py", line535, in invoke
    return callback(*args, **kwargs)
  File "/home/romel/.local/bin/lambda", line 135, in deploy
    preserve_vpc=preserve_vpc,
  File "/home/romel/.local/lib/python3.6/site-packages/aws_lambda/aws_lambda.py", line 111, in deploy
    local_package=local_package,
  File "/home/romel/.local/lib/python3.6/site-packages/aws_lambda/aws_lambda.py", line 301, in build
    local_package=local_package,
  File "/home/romel/.local/lib/python3.6/site-packages/aws_lambda/aws_lambda.py", line 438, in pip_install_to_target
    packages.extend(pkgStr.decode('utf-8').splitlines())
AttributeError: 'int' object has no attribute 'decode'
```

Y get the error `AttributeError: 'int' object has no attribute 'decode'`

**Comment by soapergem** [comment]
Whoops, yeah we introduced that problem yesterday into 3.2.5 while patching another issue. The reason it wasn't caught is because I tested it with the `-r` flag to specify a requirements.txt file. I can see that if you omit this flag it wouldn't have worked, because we were mistakenly using `subprocess.check_call()` instead of `subprocess.check_output()`.

This has been fixed in 3.2.6 which I just released. If you ensure that you can download the (new) latest release it should be fixed for you now. Thanks for reporting.
