### ISSUE TITLE
Unknown parameter in input: "Environment", must be one of: FunctionName, Runtime, Role, Handler, Code, Description, Timeout, MemorySize, Publish, VpcConfig

### ISSUE THREAD

**Issue by kedall** [nficano/python-lambda#51]
when i follow the instructions in the README and 
lambda deploy , I get the following stack trace:
```
(pylam) $ lambda deploy
Gathering pip packages
Installing boto3==1.4.1
Installing botocore==1.4.61
Installing click==6.6
Installing docutils==0.12
Installing futures==3.0.5
Installing jmespath==0.9.0
Installing pip==9.0.1
Installing pyaml==15.8.2
Installing python-dateutil==2.5.3
Installing PyYAML==3.11
Installing s3transfer==0.1.10
Installing setuptools==36.0.1
Installing six==1.10.0
Installing wheel==0.30.0a0
Installing wsgiref==0.1.2
Bundling: 'event.json'
Bundling: 'service.py'
Bundling: 'service.pyc'
Starting new HTTPS connection (1): lambda.us-west-2.amazonaws.com
Creating your new Lambda function
Starting new HTTPS connection (1): sts.amazonaws.com
Creating lambda function with name: my_lambda_function
Traceback (most recent call last):
  File "/pylam/bin/lambda", line 62, in <module>
    cli()
  File "/pylam/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/pylam/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/pylam/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/pylam/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/pylam/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/pylam/bin/lambda", line 47, in deploy
    aws_lambda.deploy(CURRENT_DIR, use_requirements, local_package)
  File "/pylam/lib/python2.7/site-packages/aws_lambda/aws_lambda.py", line 89, in deploy
    create_function(cfg, path_to_zip_file)
  File "/pylam/lib/python2.7/site-packages/aws_lambda/aws_lambda.py", line 371, in create_function
    Publish=True
  File "/pylam/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/pylam/lib/python2.7/site-packages/botocore/client.py", line 470, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/pylam/lib/python2.7/site-packages/botocore/client.py", line 523, in _convert_to_request_dict
    api_params, operation_model)
  File "/pylam/lib/python2.7/site-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Environment", must be one of: FunctionName, Runtime, Role, Handler, Code, Description, Timeout, MemorySize, Publish, VpcConfig
```

**Comment by srubin** [comment]
I was having this same issue. I fixed it by running `pip install boto3=1.4.4` and trying again.

**Comment by kedall** [comment]
confimed. thanks @srubin

**Comment by jmeekhof** [comment]
I've updated the `requirements.txt` file in the latest release to include the newer and updated versions of `boto3` and `botocore`.
