### ISSUE TITLE
Error while deploying...

### ISSUE THREAD

**Issue by sirvon** [nficano/python-lambda#55]
I'm constantly getting this error while trying to deploy to AWS..

```bash
21:00 $ lambda deploy --use-requirements
No dependency packages installed!
Bundling: 'event.json'
Bundling: 'service.py'
Creating your new Lambda function
Traceback (most recent call last):
  File "/Users/R.Thomas/.pyenv/versions/3.6.0/bin/lambda", line 62, in <module>
    cli()
  File "/Users/R.Thomas/.pyenv/versions/3.6.0/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/R.Thomas/.pyenv/versions/3.6.0/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/R.Thomas/.pyenv/versions/3.6.0/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/R.Thomas/.pyenv/versions/3.6.0/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/R.Thomas/.pyenv/versions/3.6.0/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/R.Thomas/.pyenv/versions/3.6.0/bin/lambda", line 47, in deploy
    aws_lambda.deploy(CURRENT_DIR, use_requirements, local_package)
  File "/Users/R.Thomas/.pyenv/versions/3.6.0/lib/python3.6/site-packages/aws_lambda/aws_lambda.py", line 89, in deploy
    create_function(cfg, path_to_zip_file)
  File "/Users/R.Thomas/.pyenv/versions/3.6.0/lib/python3.6/site-packages/aws_lambda/aws_lambda.py", line 341, in create_function
    byte_stream = read(path_to_zip_file)
  File "/Users/R.Thomas/.pyenv/versions/3.6.0/lib/python3.6/site-packages/aws_lambda/helpers.py", line 15, in read
    return fh.read()
  File "/Users/R.Thomas/.pyenv/versions/3.6.0/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 11: invalid start byte
```

**Comment by nficano** [comment]
Looks like your version may be out of date, make sure you run pip install -U python-lambda to verify
